version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/blog
    depends_on:
      - postgres
    command: /bin/sh start.sh
    restart: on-failure
    tty: true
    stdin_open: true

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
